services:
  chatdb-mcp-server-itc:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: chatdb-mcp-server-itc:latest
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - chat-db

networks:
  chat-db:
    external: true
