[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aioodbc>=0.5.0",
    "beautifulsoup4>=4.14.3",
    "fastmcp>=3.2.2",
    "httpx>=0.28.1",
    "langchain>=1.2.15",
    "langchain-community>=0.4.1",
    "langchain-openai>=1.1.12",
    "markdownify>=1.2.2",
    "pandas>=3.0.2",
    "pyodbc>=5.3.0",
    "python-dotenv>=1.2.2",
    "readability-lxml>=0.8.4.1",
    "sqlalchemy>=2.0.49",
]
